"""
WhatsApp delivery service.

Per the project spec, this uses the OFFICIAL WhatsApp Business Platform /
Cloud API when credentials are configured — never scraping or automating a
personal WhatsApp Web session.

If WHATSAPP_ACCESS_TOKEN / WHATSAPP_PHONE_NUMBER_ID are not configured
(e.g. local development, or a business account hasn't been approved yet),
this falls back to generating "wa.me" click-to-chat links. Those links open
WhatsApp with the alert message pre-filled — the actual send still requires
a human (the user) to tap Send, so no server-side account automation is
ever performed either way.

Never expose WHATSAPP_ACCESS_TOKEN to the frontend — it is only used here,
server-side.
"""
import logging
from typing import List
from urllib.parse import quote

import httpx

from app.config import settings

logger = logging.getLogger("safetrack.whatsapp")


def build_map_link(latitude: float, longitude: float) -> str:
    return f"https://www.google.com/maps?q={latitude},{longitude}"


def build_alert_message(
    user_name: str,
    latitude: float,
    longitude: float,
    accuracy: float | None,
    timestamp_str: str,
    is_emergency: bool = False,
) -> str:
    map_link = build_map_link(latitude, longitude)
    accuracy_str = f"Approximately {accuracy:.0f} meters" if accuracy is not None else "Unavailable"

    if is_emergency:
        return (
            "🚨 SAFETRACK EMERGENCY SOS ALERT\n\n"
            "An emergency location alert has been triggered.\n\n"
            f"👤 User: {user_name}\n\n"
            f"📍 Current Location:\n{map_link}\n\n"
            f"🕒 Time:\n{timestamp_str}\n\n"
            f"📏 GPS Accuracy:\n{accuracy_str}\n\n"
            "Please contact her immediately."
        )

    return (
        "🚨 SAFETRACK LOCATION ALERT\n\n"
        "A trusted user has shared her current location with you.\n\n"
        f"👤 User: {user_name}\n\n"
        f"📍 Current Location:\n{map_link}\n\n"
        f"🕒 Time:\n{timestamp_str}\n\n"
        f"📏 GPS Accuracy:\n{accuracy_str}\n\n"
        "Please contact her if necessary.\n"
        "This alert was generated by SafeTrack."
    )


def _is_cloud_api_configured() -> bool:
    return bool(settings.WHATSAPP_ACCESS_TOKEN and settings.WHATSAPP_PHONE_NUMBER_ID)


def build_click_to_chat_link(phone_e164: str, message: str) -> str:
    # wa.me expects digits only, no leading '+'
    digits = phone_e164.lstrip("+")
    return f"https://wa.me/{digits}?text={quote(message)}"


def send_via_cloud_api(phone_e164: str, message: str) -> bool:
    """Sends a free-form text message via the WhatsApp Business Cloud API.

    Note: outside a 24-hour customer service window, WhatsApp requires an
    approved message TEMPLATE rather than free-form text. Production
    deployments should register a template (e.g. "safety_location_alert")
    and swap this call for a template message per current WhatsApp Business
    Platform rules.
    """
    url = (
        f"https://graph.facebook.com/{settings.WHATSAPP_API_VERSION}/"
        f"{settings.WHATSAPP_PHONE_NUMBER_ID}/messages"
    )
    headers = {
        "Authorization": f"Bearer {settings.WHATSAPP_ACCESS_TOKEN}",
        "Content-Type": "application/json",
    }
    payload = {
        "messaging_product": "whatsapp",
        "to": phone_e164.lstrip("+"),
        "type": "text",
        "text": {"body": message},
    }
    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.post(url, headers=headers, json=payload)
            resp.raise_for_status()
        return True
    except httpx.HTTPError:
        logger.exception("WhatsApp Cloud API send failed for a contact")
        return False


def send_location_alert(
    contact_phones: List[str],
    user_name: str,
    latitude: float,
    longitude: float,
    accuracy: float | None,
    timestamp_str: str,
    is_emergency: bool = False,
) -> tuple[List[str], str]:
    """Returns (links_or_confirmations, delivery_mode)."""
    message = build_alert_message(user_name, latitude, longitude, accuracy, timestamp_str, is_emergency)

    if _is_cloud_api_configured():
        results = []
        for phone in contact_phones:
            ok = send_via_cloud_api(phone, message)
            results.append(f"{phone}: {'sent' if ok else 'failed'}")
        return results, "cloud_api"

    # Fallback: click-to-chat links (requires the user to tap Send).
    links = [build_click_to_chat_link(phone, message) for phone in contact_phones]
    return links, "click_to_chat"


def send_test_message(phone_e164: str) -> tuple[bool, str, str | None]:
    """Sends a test alert to verify the WhatsApp API connection.
    Returns (success, message, link_if_click_to_chat).
    """
    test_text = (
        "🛡️ SAFETRACK WHATSAPP API SERVER TEST\n\n"
        "Your WhatsApp alert gateway is online and active!\n\n"
        "This is an automated test message from SafeTrack."
    )
    if _is_cloud_api_configured():
        ok = send_via_cloud_api(phone_e164, test_text)
        if ok:
            return True, "Test message successfully sent via Meta WhatsApp Cloud API.", None
        return False, "Failed to send via WhatsApp Cloud API. Please check token or template status.", None

    link = build_click_to_chat_link(phone_e164, test_text)
    return True, "WhatsApp Cloud API credentials not configured. Generated click-to-chat link.", link
